---
version: "3"
services:
 devopsdb:
  
   image: nareshujjineni/newrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: nareshujjineni/newrepo:appimage
  
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
